// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  BackupConfig dco_decode_backup_config(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BackupConfig dco_decode_box_autoadd_backup_config(dynamic raw);

  @protected
  Credentials dco_decode_box_autoadd_credentials(dynamic raw);

  @protected
  Interaction dco_decode_box_autoadd_interaction(dynamic raw);

  @protected
  LintingConfig dco_decode_box_autoadd_linting_config(dynamic raw);

  @protected
  Member dco_decode_box_autoadd_member(dynamic raw);

  @protected
  MemberCredentials dco_decode_box_autoadd_member_credentials(dynamic raw);

  @protected
  Objective dco_decode_box_autoadd_objective(dynamic raw);

  @protected
  PublishConfig dco_decode_box_autoadd_publish_config(dynamic raw);

  @protected
  Team dco_decode_box_autoadd_team(dynamic raw);

  @protected
  TeamConfig dco_decode_box_autoadd_team_config(dynamic raw);

  @protected
  WebhookConfig dco_decode_box_autoadd_webhook_config(dynamic raw);

  @protected
  Credentials dco_decode_credentials(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  Interaction dco_decode_interaction(dynamic raw);

  @protected
  InteractionKind dco_decode_interaction_kind(dynamic raw);

  @protected
  KeyResult dco_decode_key_result(dynamic raw);

  @protected
  LintingConfig dco_decode_linting_config(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<KeyResult> dco_decode_list_key_result(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  Member dco_decode_member(dynamic raw);

  @protected
  MemberCredentials dco_decode_member_credentials(dynamic raw);

  @protected
  Objective dco_decode_objective(dynamic raw);

  @protected
  OkrVisibility dco_decode_okr_visibility(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  BackupConfig? dco_decode_opt_box_autoadd_backup_config(dynamic raw);

  @protected
  LintingConfig? dco_decode_opt_box_autoadd_linting_config(dynamic raw);

  @protected
  PublishConfig? dco_decode_opt_box_autoadd_publish_config(dynamic raw);

  @protected
  WebhookConfig? dco_decode_opt_box_autoadd_webhook_config(dynamic raw);

  @protected
  PublishConfig dco_decode_publish_config(dynamic raw);

  @protected
  Team dco_decode_team(dynamic raw);

  @protected
  TeamConfig dco_decode_team_config(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  WebhookConfig dco_decode_webhook_config(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  BackupConfig sse_decode_backup_config(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BackupConfig sse_decode_box_autoadd_backup_config(
      SseDeserializer deserializer);

  @protected
  Credentials sse_decode_box_autoadd_credentials(SseDeserializer deserializer);

  @protected
  Interaction sse_decode_box_autoadd_interaction(SseDeserializer deserializer);

  @protected
  LintingConfig sse_decode_box_autoadd_linting_config(
      SseDeserializer deserializer);

  @protected
  Member sse_decode_box_autoadd_member(SseDeserializer deserializer);

  @protected
  MemberCredentials sse_decode_box_autoadd_member_credentials(
      SseDeserializer deserializer);

  @protected
  Objective sse_decode_box_autoadd_objective(SseDeserializer deserializer);

  @protected
  PublishConfig sse_decode_box_autoadd_publish_config(
      SseDeserializer deserializer);

  @protected
  Team sse_decode_box_autoadd_team(SseDeserializer deserializer);

  @protected
  TeamConfig sse_decode_box_autoadd_team_config(SseDeserializer deserializer);

  @protected
  WebhookConfig sse_decode_box_autoadd_webhook_config(
      SseDeserializer deserializer);

  @protected
  Credentials sse_decode_credentials(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  Interaction sse_decode_interaction(SseDeserializer deserializer);

  @protected
  InteractionKind sse_decode_interaction_kind(SseDeserializer deserializer);

  @protected
  KeyResult sse_decode_key_result(SseDeserializer deserializer);

  @protected
  LintingConfig sse_decode_linting_config(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<KeyResult> sse_decode_list_key_result(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  Member sse_decode_member(SseDeserializer deserializer);

  @protected
  MemberCredentials sse_decode_member_credentials(SseDeserializer deserializer);

  @protected
  Objective sse_decode_objective(SseDeserializer deserializer);

  @protected
  OkrVisibility sse_decode_okr_visibility(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  BackupConfig? sse_decode_opt_box_autoadd_backup_config(
      SseDeserializer deserializer);

  @protected
  LintingConfig? sse_decode_opt_box_autoadd_linting_config(
      SseDeserializer deserializer);

  @protected
  PublishConfig? sse_decode_opt_box_autoadd_publish_config(
      SseDeserializer deserializer);

  @protected
  WebhookConfig? sse_decode_opt_box_autoadd_webhook_config(
      SseDeserializer deserializer);

  @protected
  PublishConfig sse_decode_publish_config(SseDeserializer deserializer);

  @protected
  Team sse_decode_team(SseDeserializer deserializer);

  @protected
  TeamConfig sse_decode_team_config(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  WebhookConfig sse_decode_webhook_config(SseDeserializer deserializer);

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_prim_u_8_strict(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<wire_cst_backup_config> cst_encode_box_autoadd_backup_config(
      BackupConfig raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_backup_config();
    cst_api_fill_to_wire_backup_config(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_credentials> cst_encode_box_autoadd_credentials(
      Credentials raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_credentials();
    cst_api_fill_to_wire_credentials(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_interaction> cst_encode_box_autoadd_interaction(
      Interaction raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_interaction();
    cst_api_fill_to_wire_interaction(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_linting_config> cst_encode_box_autoadd_linting_config(
      LintingConfig raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_linting_config();
    cst_api_fill_to_wire_linting_config(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_member> cst_encode_box_autoadd_member(Member raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_member();
    cst_api_fill_to_wire_member(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_member_credentials>
      cst_encode_box_autoadd_member_credentials(MemberCredentials raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_member_credentials();
    cst_api_fill_to_wire_member_credentials(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_objective> cst_encode_box_autoadd_objective(
      Objective raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_objective();
    cst_api_fill_to_wire_objective(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_publish_config> cst_encode_box_autoadd_publish_config(
      PublishConfig raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_publish_config();
    cst_api_fill_to_wire_publish_config(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_team> cst_encode_box_autoadd_team(Team raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_team();
    cst_api_fill_to_wire_team(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_team_config> cst_encode_box_autoadd_team_config(
      TeamConfig raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_team_config();
    cst_api_fill_to_wire_team_config(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_webhook_config> cst_encode_box_autoadd_webhook_config(
      WebhookConfig raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_webhook_config();
    cst_api_fill_to_wire_webhook_config(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_list_String> cst_encode_list_String(List<String> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_String(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      ans.ref.ptr[i] = cst_encode_String(raw[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_key_result> cst_encode_list_key_result(
      List<KeyResult> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_key_result(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_key_result(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_list_prim_u_8_strict(
      Uint8List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_opt_String(
      String? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_String(raw);
  }

  @protected
  ffi.Pointer<wire_cst_backup_config> cst_encode_opt_box_autoadd_backup_config(
      BackupConfig? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null
        ? ffi.nullptr
        : cst_encode_box_autoadd_backup_config(raw);
  }

  @protected
  ffi.Pointer<wire_cst_linting_config>
      cst_encode_opt_box_autoadd_linting_config(LintingConfig? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null
        ? ffi.nullptr
        : cst_encode_box_autoadd_linting_config(raw);
  }

  @protected
  ffi.Pointer<wire_cst_publish_config>
      cst_encode_opt_box_autoadd_publish_config(PublishConfig? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null
        ? ffi.nullptr
        : cst_encode_box_autoadd_publish_config(raw);
  }

  @protected
  ffi.Pointer<wire_cst_webhook_config>
      cst_encode_opt_box_autoadd_webhook_config(WebhookConfig? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null
        ? ffi.nullptr
        : cst_encode_box_autoadd_webhook_config(raw);
  }

  @protected
  void cst_api_fill_to_wire_backup_config(
      BackupConfig apiObj, wire_cst_backup_config wireObj) {
    wireObj.protected_branch = cst_encode_opt_String(apiObj.protectedBranch);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_backup_config(
      BackupConfig apiObj, ffi.Pointer<wire_cst_backup_config> wireObj) {
    cst_api_fill_to_wire_backup_config(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_credentials(
      Credentials apiObj, ffi.Pointer<wire_cst_credentials> wireObj) {
    cst_api_fill_to_wire_credentials(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_interaction(
      Interaction apiObj, ffi.Pointer<wire_cst_interaction> wireObj) {
    cst_api_fill_to_wire_interaction(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_linting_config(
      LintingConfig apiObj, ffi.Pointer<wire_cst_linting_config> wireObj) {
    cst_api_fill_to_wire_linting_config(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_member(
      Member apiObj, ffi.Pointer<wire_cst_member> wireObj) {
    cst_api_fill_to_wire_member(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_member_credentials(
      MemberCredentials apiObj,
      ffi.Pointer<wire_cst_member_credentials> wireObj) {
    cst_api_fill_to_wire_member_credentials(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_objective(
      Objective apiObj, ffi.Pointer<wire_cst_objective> wireObj) {
    cst_api_fill_to_wire_objective(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_publish_config(
      PublishConfig apiObj, ffi.Pointer<wire_cst_publish_config> wireObj) {
    cst_api_fill_to_wire_publish_config(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_team(
      Team apiObj, ffi.Pointer<wire_cst_team> wireObj) {
    cst_api_fill_to_wire_team(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_team_config(
      TeamConfig apiObj, ffi.Pointer<wire_cst_team_config> wireObj) {
    cst_api_fill_to_wire_team_config(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_webhook_config(
      WebhookConfig apiObj, ffi.Pointer<wire_cst_webhook_config> wireObj) {
    cst_api_fill_to_wire_webhook_config(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_credentials(
      Credentials apiObj, wire_cst_credentials wireObj) {
    wireObj.salt = cst_encode_String(apiObj.salt);
    wireObj.pincode_hash = cst_encode_String(apiObj.pincodeHash);
  }

  @protected
  void cst_api_fill_to_wire_interaction(
      Interaction apiObj, wire_cst_interaction wireObj) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.kind = cst_encode_interaction_kind(apiObj.kind);
    wireObj.from = cst_encode_String(apiObj.from);
    wireObj.with_members = cst_encode_list_String(apiObj.withMembers);
    wireObj.note = cst_encode_String(apiObj.note);
    wireObj.timestamp = cst_encode_String(apiObj.timestamp);
    wireObj.shared = cst_encode_bool(apiObj.shared);
  }

  @protected
  void cst_api_fill_to_wire_key_result(
      KeyResult apiObj, wire_cst_key_result wireObj) {
    wireObj.description = cst_encode_String(apiObj.description);
    wireObj.progress = cst_encode_f_32(apiObj.progress);
    wireObj.notes = cst_encode_opt_String(apiObj.notes);
  }

  @protected
  void cst_api_fill_to_wire_linting_config(
      LintingConfig apiObj, wire_cst_linting_config wireObj) {
    wireObj.enabled = cst_encode_bool(apiObj.enabled);
    wireObj.target_branch = cst_encode_opt_String(apiObj.targetBranch);
  }

  @protected
  void cst_api_fill_to_wire_member(Member apiObj, wire_cst_member wireObj) {
    wireObj.email = cst_encode_String(apiObj.email);
    wireObj.name = cst_encode_opt_String(apiObj.name);
    wireObj.bio = cst_encode_opt_String(apiObj.bio);
    wireObj.timezone = cst_encode_opt_String(apiObj.timezone);
  }

  @protected
  void cst_api_fill_to_wire_member_credentials(
      MemberCredentials apiObj, wire_cst_member_credentials wireObj) {
    wireObj.email = cst_encode_String(apiObj.email);
    cst_api_fill_to_wire_credentials(apiObj.credentials, wireObj.credentials);
  }

  @protected
  void cst_api_fill_to_wire_objective(
      Objective apiObj, wire_cst_objective wireObj) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.title = cst_encode_String(apiObj.title);
    wireObj.description = cst_encode_opt_String(apiObj.description);
    wireObj.key_results = cst_encode_list_key_result(apiObj.keyResults);
    wireObj.visibility = cst_encode_okr_visibility(apiObj.visibility);
    wireObj.owner = cst_encode_opt_String(apiObj.owner);
    wireObj.quarter = cst_encode_opt_String(apiObj.quarter);
  }

  @protected
  void cst_api_fill_to_wire_publish_config(
      PublishConfig apiObj, wire_cst_publish_config wireObj) {
    wireObj.manifesto = cst_encode_opt_String(apiObj.manifesto);
    wireObj.vision = cst_encode_opt_String(apiObj.vision);
    wireObj.okrs = cst_encode_opt_String(apiObj.okrs);
  }

  @protected
  void cst_api_fill_to_wire_team(Team apiObj, wire_cst_team wireObj) {
    wireObj.name = cst_encode_String(apiObj.name);
    wireObj.manifesto = cst_encode_opt_String(apiObj.manifesto);
    wireObj.vision = cst_encode_opt_String(apiObj.vision);
    wireObj.leaders = cst_encode_list_String(apiObj.leaders);
    wireObj.members = cst_encode_list_String(apiObj.members);
  }

  @protected
  void cst_api_fill_to_wire_team_config(
      TeamConfig apiObj, wire_cst_team_config wireObj) {
    wireObj.publish = cst_encode_opt_box_autoadd_publish_config(apiObj.publish);
    wireObj.webhooks =
        cst_encode_opt_box_autoadd_webhook_config(apiObj.webhooks);
    wireObj.linting = cst_encode_opt_box_autoadd_linting_config(apiObj.linting);
    wireObj.backup = cst_encode_opt_box_autoadd_backup_config(apiObj.backup);
  }

  @protected
  void cst_api_fill_to_wire_webhook_config(
      WebhookConfig apiObj, wire_cst_webhook_config wireObj) {
    wireObj.discord = cst_encode_opt_String(apiObj.discord);
    wireObj.slack = cst_encode_opt_String(apiObj.slack);
    wireObj.signal = cst_encode_opt_String(apiObj.signal);
  }

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  double cst_encode_f_32(double raw);

  @protected
  int cst_encode_i_32(int raw);

  @protected
  int cst_encode_interaction_kind(InteractionKind raw);

  @protected
  int cst_encode_okr_visibility(OkrVisibility raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_backup_config(BackupConfig self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_backup_config(
      BackupConfig self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_credentials(
      Credentials self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_interaction(
      Interaction self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_linting_config(
      LintingConfig self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_member(Member self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_member_credentials(
      MemberCredentials self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_objective(
      Objective self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_publish_config(
      PublishConfig self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_team(Team self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_team_config(
      TeamConfig self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_webhook_config(
      WebhookConfig self, SseSerializer serializer);

  @protected
  void sse_encode_credentials(Credentials self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_interaction(Interaction self, SseSerializer serializer);

  @protected
  void sse_encode_interaction_kind(
      InteractionKind self, SseSerializer serializer);

  @protected
  void sse_encode_key_result(KeyResult self, SseSerializer serializer);

  @protected
  void sse_encode_linting_config(LintingConfig self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_key_result(
      List<KeyResult> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_member(Member self, SseSerializer serializer);

  @protected
  void sse_encode_member_credentials(
      MemberCredentials self, SseSerializer serializer);

  @protected
  void sse_encode_objective(Objective self, SseSerializer serializer);

  @protected
  void sse_encode_okr_visibility(OkrVisibility self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_backup_config(
      BackupConfig? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_linting_config(
      LintingConfig? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_publish_config(
      PublishConfig? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_webhook_config(
      WebhookConfig? self, SseSerializer serializer);

  @protected
  void sse_encode_publish_config(PublishConfig self, SseSerializer serializer);

  @protected
  void sse_encode_team(Team self, SseSerializer serializer);

  @protected
  void sse_encode_team_config(TeamConfig self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_webhook_config(WebhookConfig self, SseSerializer serializer);
}

// Section: wire_class

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint

/// generated by flutter_rust_bridge
class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  RustLibWire.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  void store_dart_post_cobject(DartPostCObjectFnType ptr) {
    return _store_dart_post_cobject(ptr);
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
    'store_dart_post_cobject',
  );
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  WireSyncRust2DartDco wire__crate__api__credentials_create(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> pincode,
  ) {
    return _wire__crate__api__credentials_create(pincode);
  }

  late final _wire__crate__api__credentials_createPtr = _lookup<
      ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>>('frbgen_interactions_wire__crate__api__credentials_create');
  late final _wire__crate__api__credentials_create =
      _wire__crate__api__credentials_createPtr.asFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>();

  WireSyncRust2DartDco wire__crate__api__credentials_from_yaml(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> yaml,
  ) {
    return _wire__crate__api__credentials_from_yaml(yaml);
  }

  late final _wire__crate__api__credentials_from_yamlPtr = _lookup<
      ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>>('frbgen_interactions_wire__crate__api__credentials_from_yaml');
  late final _wire__crate__api__credentials_from_yaml =
      _wire__crate__api__credentials_from_yamlPtr.asFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>();

  WireSyncRust2DartDco wire__crate__api__credentials_to_yaml(
    ffi.Pointer<wire_cst_credentials> credentials,
  ) {
    return _wire__crate__api__credentials_to_yaml(credentials);
  }

  late final _wire__crate__api__credentials_to_yamlPtr = _lookup<
          ffi.NativeFunction<
              WireSyncRust2DartDco Function(
                  ffi.Pointer<wire_cst_credentials>)>>(
      'frbgen_interactions_wire__crate__api__credentials_to_yaml');
  late final _wire__crate__api__credentials_to_yaml =
      _wire__crate__api__credentials_to_yamlPtr.asFunction<
          WireSyncRust2DartDco Function(ffi.Pointer<wire_cst_credentials>)>();

  WireSyncRust2DartDco wire__crate__api__credentials_verify(
    ffi.Pointer<wire_cst_credentials> that,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> pincode,
  ) {
    return _wire__crate__api__credentials_verify(that, pincode);
  }

  late final _wire__crate__api__credentials_verifyPtr = _lookup<
      ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_credentials>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>>('frbgen_interactions_wire__crate__api__credentials_verify');
  late final _wire__crate__api__credentials_verify =
      _wire__crate__api__credentials_verifyPtr.asFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_credentials>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>();

  WireSyncRust2DartDco wire__crate__api__interaction_appreciation(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> from,
    ffi.Pointer<wire_cst_list_String> with_members,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> note,
  ) {
    return _wire__crate__api__interaction_appreciation(
      from,
      with_members,
      note,
    );
  }

  late final _wire__crate__api__interaction_appreciationPtr = _lookup<
      ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_String>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>>('frbgen_interactions_wire__crate__api__interaction_appreciation');
  late final _wire__crate__api__interaction_appreciation =
      _wire__crate__api__interaction_appreciationPtr.asFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_String>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>();

  WireSyncRust2DartDco wire__crate__api__interaction_create(
    int kind,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> from,
    ffi.Pointer<wire_cst_list_String> with_members,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> note,
  ) {
    return _wire__crate__api__interaction_create(
      kind,
      from,
      with_members,
      note,
    );
  }

  late final _wire__crate__api__interaction_createPtr = _lookup<
      ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Int32,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_String>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>>('frbgen_interactions_wire__crate__api__interaction_create');
  late final _wire__crate__api__interaction_create =
      _wire__crate__api__interaction_createPtr.asFunction<
          WireSyncRust2DartDco Function(
            int,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_String>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>();

  WireSyncRust2DartDco wire__crate__api__interaction_feedback(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> from,
    ffi.Pointer<wire_cst_list_String> with_members,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> note,
  ) {
    return _wire__crate__api__interaction_feedback(from, with_members, note);
  }

  late final _wire__crate__api__interaction_feedbackPtr = _lookup<
      ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_String>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>>('frbgen_interactions_wire__crate__api__interaction_feedback');
  late final _wire__crate__api__interaction_feedback =
      _wire__crate__api__interaction_feedbackPtr.asFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_String>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>();

  WireSyncRust2DartDco wire__crate__api__interaction_from_yaml(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> yaml,
  ) {
    return _wire__crate__api__interaction_from_yaml(yaml);
  }

  late final _wire__crate__api__interaction_from_yamlPtr = _lookup<
      ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>>('frbgen_interactions_wire__crate__api__interaction_from_yaml');
  late final _wire__crate__api__interaction_from_yaml =
      _wire__crate__api__interaction_from_yamlPtr.asFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>();

  WireSyncRust2DartDco wire__crate__api__interaction_kind_label(int that) {
    return _wire__crate__api__interaction_kind_label(that);
  }

  late final _wire__crate__api__interaction_kind_labelPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function(ffi.Int32)>>(
    'frbgen_interactions_wire__crate__api__interaction_kind_label',
  );
  late final _wire__crate__api__interaction_kind_label =
      _wire__crate__api__interaction_kind_labelPtr
          .asFunction<WireSyncRust2DartDco Function(int)>();

  WireSyncRust2DartDco wire__crate__api__interaction_to_yaml(
    ffi.Pointer<wire_cst_interaction> interaction,
  ) {
    return _wire__crate__api__interaction_to_yaml(interaction);
  }

  late final _wire__crate__api__interaction_to_yamlPtr = _lookup<
          ffi.NativeFunction<
              WireSyncRust2DartDco Function(
                  ffi.Pointer<wire_cst_interaction>)>>(
      'frbgen_interactions_wire__crate__api__interaction_to_yaml');
  late final _wire__crate__api__interaction_to_yaml =
      _wire__crate__api__interaction_to_yamlPtr.asFunction<
          WireSyncRust2DartDco Function(ffi.Pointer<wire_cst_interaction>)>();

  WireSyncRust2DartDco wire__crate__api__key_result_clamp_progress(
    double progress,
  ) {
    return _wire__crate__api__key_result_clamp_progress(progress);
  }

  late final _wire__crate__api__key_result_clamp_progressPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function(ffi.Float)>>(
    'frbgen_interactions_wire__crate__api__key_result_clamp_progress',
  );
  late final _wire__crate__api__key_result_clamp_progress =
      _wire__crate__api__key_result_clamp_progressPtr
          .asFunction<WireSyncRust2DartDco Function(double)>();

  WireSyncRust2DartDco wire__crate__api__key_result_create(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> description,
  ) {
    return _wire__crate__api__key_result_create(description);
  }

  late final _wire__crate__api__key_result_createPtr = _lookup<
      ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>>('frbgen_interactions_wire__crate__api__key_result_create');
  late final _wire__crate__api__key_result_create =
      _wire__crate__api__key_result_createPtr.asFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>();

  WireSyncRust2DartDco wire__crate__api__member_create(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> email,
  ) {
    return _wire__crate__api__member_create(email);
  }

  late final _wire__crate__api__member_createPtr = _lookup<
      ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>>('frbgen_interactions_wire__crate__api__member_create');
  late final _wire__crate__api__member_create =
      _wire__crate__api__member_createPtr.asFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>();

  WireSyncRust2DartDco wire__crate__api__member_credentials_create(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> email,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> pincode,
  ) {
    return _wire__crate__api__member_credentials_create(email, pincode);
  }

  late final _wire__crate__api__member_credentials_createPtr = _lookup<
          ffi.NativeFunction<
              WireSyncRust2DartDco Function(
                ffi.Pointer<wire_cst_list_prim_u_8_strict>,
                ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              )>>(
      'frbgen_interactions_wire__crate__api__member_credentials_create');
  late final _wire__crate__api__member_credentials_create =
      _wire__crate__api__member_credentials_createPtr.asFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>();

  WireSyncRust2DartDco wire__crate__api__member_credentials_from_yaml(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> yaml,
  ) {
    return _wire__crate__api__member_credentials_from_yaml(yaml);
  }

  late final _wire__crate__api__member_credentials_from_yamlPtr = _lookup<
          ffi.NativeFunction<
              WireSyncRust2DartDco Function(
                ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              )>>(
      'frbgen_interactions_wire__crate__api__member_credentials_from_yaml');
  late final _wire__crate__api__member_credentials_from_yaml =
      _wire__crate__api__member_credentials_from_yamlPtr.asFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>();

  WireSyncRust2DartDco wire__crate__api__member_credentials_to_yaml(
    ffi.Pointer<wire_cst_member_credentials> creds,
  ) {
    return _wire__crate__api__member_credentials_to_yaml(creds);
  }

  late final _wire__crate__api__member_credentials_to_yamlPtr = _lookup<
          ffi.NativeFunction<
              WireSyncRust2DartDco Function(
                ffi.Pointer<wire_cst_member_credentials>,
              )>>(
      'frbgen_interactions_wire__crate__api__member_credentials_to_yaml');
  late final _wire__crate__api__member_credentials_to_yaml =
      _wire__crate__api__member_credentials_to_yamlPtr.asFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_member_credentials>,
          )>();

  WireSyncRust2DartDco wire__crate__api__member_credentials_verify(
    ffi.Pointer<wire_cst_member_credentials> that,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> pincode,
  ) {
    return _wire__crate__api__member_credentials_verify(that, pincode);
  }

  late final _wire__crate__api__member_credentials_verifyPtr = _lookup<
          ffi.NativeFunction<
              WireSyncRust2DartDco Function(
                ffi.Pointer<wire_cst_member_credentials>,
                ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              )>>(
      'frbgen_interactions_wire__crate__api__member_credentials_verify');
  late final _wire__crate__api__member_credentials_verify =
      _wire__crate__api__member_credentials_verifyPtr.asFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_member_credentials>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>();

  WireSyncRust2DartDco wire__crate__api__member_display_name(
    ffi.Pointer<wire_cst_member> that,
  ) {
    return _wire__crate__api__member_display_name(that);
  }

  late final _wire__crate__api__member_display_namePtr = _lookup<
          ffi.NativeFunction<
              WireSyncRust2DartDco Function(ffi.Pointer<wire_cst_member>)>>(
      'frbgen_interactions_wire__crate__api__member_display_name');
  late final _wire__crate__api__member_display_name =
      _wire__crate__api__member_display_namePtr.asFunction<
          WireSyncRust2DartDco Function(ffi.Pointer<wire_cst_member>)>();

  WireSyncRust2DartDco wire__crate__api__member_from_yaml(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> yaml,
  ) {
    return _wire__crate__api__member_from_yaml(yaml);
  }

  late final _wire__crate__api__member_from_yamlPtr = _lookup<
      ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>>('frbgen_interactions_wire__crate__api__member_from_yaml');
  late final _wire__crate__api__member_from_yaml =
      _wire__crate__api__member_from_yamlPtr.asFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>();

  WireSyncRust2DartDco wire__crate__api__member_to_yaml(
    ffi.Pointer<wire_cst_member> member,
  ) {
    return _wire__crate__api__member_to_yaml(member);
  }

  late final _wire__crate__api__member_to_yamlPtr = _lookup<
          ffi.NativeFunction<
              WireSyncRust2DartDco Function(ffi.Pointer<wire_cst_member>)>>(
      'frbgen_interactions_wire__crate__api__member_to_yaml');
  late final _wire__crate__api__member_to_yaml =
      _wire__crate__api__member_to_yamlPtr.asFunction<
          WireSyncRust2DartDco Function(ffi.Pointer<wire_cst_member>)>();

  WireSyncRust2DartDco wire__crate__api__objective_create(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> title,
  ) {
    return _wire__crate__api__objective_create(title);
  }

  late final _wire__crate__api__objective_createPtr = _lookup<
      ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>>('frbgen_interactions_wire__crate__api__objective_create');
  late final _wire__crate__api__objective_create =
      _wire__crate__api__objective_createPtr.asFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>();

  WireSyncRust2DartDco wire__crate__api__objective_from_yaml(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> yaml,
  ) {
    return _wire__crate__api__objective_from_yaml(yaml);
  }

  late final _wire__crate__api__objective_from_yamlPtr = _lookup<
      ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>>('frbgen_interactions_wire__crate__api__objective_from_yaml');
  late final _wire__crate__api__objective_from_yaml =
      _wire__crate__api__objective_from_yamlPtr.asFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>();

  WireSyncRust2DartDco wire__crate__api__objective_overall_progress(
    ffi.Pointer<wire_cst_objective> that,
  ) {
    return _wire__crate__api__objective_overall_progress(that);
  }

  late final _wire__crate__api__objective_overall_progressPtr = _lookup<
          ffi.NativeFunction<
              WireSyncRust2DartDco Function(ffi.Pointer<wire_cst_objective>)>>(
      'frbgen_interactions_wire__crate__api__objective_overall_progress');
  late final _wire__crate__api__objective_overall_progress =
      _wire__crate__api__objective_overall_progressPtr.asFunction<
          WireSyncRust2DartDco Function(ffi.Pointer<wire_cst_objective>)>();

  WireSyncRust2DartDco wire__crate__api__objective_to_yaml(
    ffi.Pointer<wire_cst_objective> objective,
  ) {
    return _wire__crate__api__objective_to_yaml(objective);
  }

  late final _wire__crate__api__objective_to_yamlPtr = _lookup<
          ffi.NativeFunction<
              WireSyncRust2DartDco Function(ffi.Pointer<wire_cst_objective>)>>(
      'frbgen_interactions_wire__crate__api__objective_to_yaml');
  late final _wire__crate__api__objective_to_yaml =
      _wire__crate__api__objective_to_yamlPtr.asFunction<
          WireSyncRust2DartDco Function(ffi.Pointer<wire_cst_objective>)>();

  void wire__crate__api__okr_visibility_default(int port_) {
    return _wire__crate__api__okr_visibility_default(port_);
  }

  late final _wire__crate__api__okr_visibility_defaultPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
    'frbgen_interactions_wire__crate__api__okr_visibility_default',
  );
  late final _wire__crate__api__okr_visibility_default =
      _wire__crate__api__okr_visibility_defaultPtr
          .asFunction<void Function(int)>();

  WireSyncRust2DartDco wire__crate__api__team_config_create() {
    return _wire__crate__api__team_config_create();
  }

  late final _wire__crate__api__team_config_createPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
    'frbgen_interactions_wire__crate__api__team_config_create',
  );
  late final _wire__crate__api__team_config_create =
      _wire__crate__api__team_config_createPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  WireSyncRust2DartDco wire__crate__api__team_config_from_yaml(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> yaml,
  ) {
    return _wire__crate__api__team_config_from_yaml(yaml);
  }

  late final _wire__crate__api__team_config_from_yamlPtr = _lookup<
      ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>>('frbgen_interactions_wire__crate__api__team_config_from_yaml');
  late final _wire__crate__api__team_config_from_yaml =
      _wire__crate__api__team_config_from_yamlPtr.asFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>();

  WireSyncRust2DartDco wire__crate__api__team_config_to_yaml(
    ffi.Pointer<wire_cst_team_config> config,
  ) {
    return _wire__crate__api__team_config_to_yaml(config);
  }

  late final _wire__crate__api__team_config_to_yamlPtr = _lookup<
          ffi.NativeFunction<
              WireSyncRust2DartDco Function(
                  ffi.Pointer<wire_cst_team_config>)>>(
      'frbgen_interactions_wire__crate__api__team_config_to_yaml');
  late final _wire__crate__api__team_config_to_yaml =
      _wire__crate__api__team_config_to_yamlPtr.asFunction<
          WireSyncRust2DartDco Function(ffi.Pointer<wire_cst_team_config>)>();

  WireSyncRust2DartDco wire__crate__api__team_config_with_defaults() {
    return _wire__crate__api__team_config_with_defaults();
  }

  late final _wire__crate__api__team_config_with_defaultsPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
    'frbgen_interactions_wire__crate__api__team_config_with_defaults',
  );
  late final _wire__crate__api__team_config_with_defaults =
      _wire__crate__api__team_config_with_defaultsPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  WireSyncRust2DartDco wire__crate__api__team_create(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> name,
  ) {
    return _wire__crate__api__team_create(name);
  }

  late final _wire__crate__api__team_createPtr = _lookup<
      ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>>('frbgen_interactions_wire__crate__api__team_create');
  late final _wire__crate__api__team_create =
      _wire__crate__api__team_createPtr.asFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>();

  WireSyncRust2DartDco wire__crate__api__team_from_yaml(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> yaml,
  ) {
    return _wire__crate__api__team_from_yaml(yaml);
  }

  late final _wire__crate__api__team_from_yamlPtr = _lookup<
      ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>>('frbgen_interactions_wire__crate__api__team_from_yaml');
  late final _wire__crate__api__team_from_yaml =
      _wire__crate__api__team_from_yamlPtr.asFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>();

  WireSyncRust2DartDco wire__crate__api__team_is_leader(
    ffi.Pointer<wire_cst_team> that,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> email,
  ) {
    return _wire__crate__api__team_is_leader(that, email);
  }

  late final _wire__crate__api__team_is_leaderPtr = _lookup<
      ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_team>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>>('frbgen_interactions_wire__crate__api__team_is_leader');
  late final _wire__crate__api__team_is_leader =
      _wire__crate__api__team_is_leaderPtr.asFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_team>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>();

  WireSyncRust2DartDco wire__crate__api__team_is_member(
    ffi.Pointer<wire_cst_team> that,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> email,
  ) {
    return _wire__crate__api__team_is_member(that, email);
  }

  late final _wire__crate__api__team_is_memberPtr = _lookup<
      ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_team>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>>('frbgen_interactions_wire__crate__api__team_is_member');
  late final _wire__crate__api__team_is_member =
      _wire__crate__api__team_is_memberPtr.asFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_team>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>();

  WireSyncRust2DartDco wire__crate__api__team_to_yaml(
    ffi.Pointer<wire_cst_team> team,
  ) {
    return _wire__crate__api__team_to_yaml(team);
  }

  late final _wire__crate__api__team_to_yamlPtr = _lookup<
          ffi.NativeFunction<
              WireSyncRust2DartDco Function(ffi.Pointer<wire_cst_team>)>>(
      'frbgen_interactions_wire__crate__api__team_to_yaml');
  late final _wire__crate__api__team_to_yaml =
      _wire__crate__api__team_to_yamlPtr.asFunction<
          WireSyncRust2DartDco Function(ffi.Pointer<wire_cst_team>)>();

  ffi.Pointer<wire_cst_backup_config> cst_new_box_autoadd_backup_config() {
    return _cst_new_box_autoadd_backup_config();
  }

  late final _cst_new_box_autoadd_backup_configPtr = _lookup<
          ffi.NativeFunction<ffi.Pointer<wire_cst_backup_config> Function()>>(
      'frbgen_interactions_cst_new_box_autoadd_backup_config');
  late final _cst_new_box_autoadd_backup_config =
      _cst_new_box_autoadd_backup_configPtr
          .asFunction<ffi.Pointer<wire_cst_backup_config> Function()>();

  ffi.Pointer<wire_cst_credentials> cst_new_box_autoadd_credentials() {
    return _cst_new_box_autoadd_credentials();
  }

  late final _cst_new_box_autoadd_credentialsPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_credentials> Function()>>(
    'frbgen_interactions_cst_new_box_autoadd_credentials',
  );
  late final _cst_new_box_autoadd_credentials =
      _cst_new_box_autoadd_credentialsPtr
          .asFunction<ffi.Pointer<wire_cst_credentials> Function()>();

  ffi.Pointer<wire_cst_interaction> cst_new_box_autoadd_interaction() {
    return _cst_new_box_autoadd_interaction();
  }

  late final _cst_new_box_autoadd_interactionPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_interaction> Function()>>(
    'frbgen_interactions_cst_new_box_autoadd_interaction',
  );
  late final _cst_new_box_autoadd_interaction =
      _cst_new_box_autoadd_interactionPtr
          .asFunction<ffi.Pointer<wire_cst_interaction> Function()>();

  ffi.Pointer<wire_cst_linting_config> cst_new_box_autoadd_linting_config() {
    return _cst_new_box_autoadd_linting_config();
  }

  late final _cst_new_box_autoadd_linting_configPtr = _lookup<
          ffi.NativeFunction<ffi.Pointer<wire_cst_linting_config> Function()>>(
      'frbgen_interactions_cst_new_box_autoadd_linting_config');
  late final _cst_new_box_autoadd_linting_config =
      _cst_new_box_autoadd_linting_configPtr
          .asFunction<ffi.Pointer<wire_cst_linting_config> Function()>();

  ffi.Pointer<wire_cst_member> cst_new_box_autoadd_member() {
    return _cst_new_box_autoadd_member();
  }

  late final _cst_new_box_autoadd_memberPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_member> Function()>>(
    'frbgen_interactions_cst_new_box_autoadd_member',
  );
  late final _cst_new_box_autoadd_member = _cst_new_box_autoadd_memberPtr
      .asFunction<ffi.Pointer<wire_cst_member> Function()>();

  ffi.Pointer<wire_cst_member_credentials>
      cst_new_box_autoadd_member_credentials() {
    return _cst_new_box_autoadd_member_credentials();
  }

  late final _cst_new_box_autoadd_member_credentialsPtr = _lookup<
          ffi
          .NativeFunction<ffi.Pointer<wire_cst_member_credentials> Function()>>(
      'frbgen_interactions_cst_new_box_autoadd_member_credentials');
  late final _cst_new_box_autoadd_member_credentials =
      _cst_new_box_autoadd_member_credentialsPtr
          .asFunction<ffi.Pointer<wire_cst_member_credentials> Function()>();

  ffi.Pointer<wire_cst_objective> cst_new_box_autoadd_objective() {
    return _cst_new_box_autoadd_objective();
  }

  late final _cst_new_box_autoadd_objectivePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_objective> Function()>>(
    'frbgen_interactions_cst_new_box_autoadd_objective',
  );
  late final _cst_new_box_autoadd_objective = _cst_new_box_autoadd_objectivePtr
      .asFunction<ffi.Pointer<wire_cst_objective> Function()>();

  ffi.Pointer<wire_cst_publish_config> cst_new_box_autoadd_publish_config() {
    return _cst_new_box_autoadd_publish_config();
  }

  late final _cst_new_box_autoadd_publish_configPtr = _lookup<
          ffi.NativeFunction<ffi.Pointer<wire_cst_publish_config> Function()>>(
      'frbgen_interactions_cst_new_box_autoadd_publish_config');
  late final _cst_new_box_autoadd_publish_config =
      _cst_new_box_autoadd_publish_configPtr
          .asFunction<ffi.Pointer<wire_cst_publish_config> Function()>();

  ffi.Pointer<wire_cst_team> cst_new_box_autoadd_team() {
    return _cst_new_box_autoadd_team();
  }

  late final _cst_new_box_autoadd_teamPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_team> Function()>>(
    'frbgen_interactions_cst_new_box_autoadd_team',
  );
  late final _cst_new_box_autoadd_team = _cst_new_box_autoadd_teamPtr
      .asFunction<ffi.Pointer<wire_cst_team> Function()>();

  ffi.Pointer<wire_cst_team_config> cst_new_box_autoadd_team_config() {
    return _cst_new_box_autoadd_team_config();
  }

  late final _cst_new_box_autoadd_team_configPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_team_config> Function()>>(
    'frbgen_interactions_cst_new_box_autoadd_team_config',
  );
  late final _cst_new_box_autoadd_team_config =
      _cst_new_box_autoadd_team_configPtr
          .asFunction<ffi.Pointer<wire_cst_team_config> Function()>();

  ffi.Pointer<wire_cst_webhook_config> cst_new_box_autoadd_webhook_config() {
    return _cst_new_box_autoadd_webhook_config();
  }

  late final _cst_new_box_autoadd_webhook_configPtr = _lookup<
          ffi.NativeFunction<ffi.Pointer<wire_cst_webhook_config> Function()>>(
      'frbgen_interactions_cst_new_box_autoadd_webhook_config');
  late final _cst_new_box_autoadd_webhook_config =
      _cst_new_box_autoadd_webhook_configPtr
          .asFunction<ffi.Pointer<wire_cst_webhook_config> Function()>();

  ffi.Pointer<wire_cst_list_String> cst_new_list_String(int len) {
    return _cst_new_list_String(len);
  }

  late final _cst_new_list_StringPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_String> Function(
              ffi.Int32)>>('frbgen_interactions_cst_new_list_String');
  late final _cst_new_list_String = _cst_new_list_StringPtr
      .asFunction<ffi.Pointer<wire_cst_list_String> Function(int)>();

  ffi.Pointer<wire_cst_list_key_result> cst_new_list_key_result(int len) {
    return _cst_new_list_key_result(len);
  }

  late final _cst_new_list_key_resultPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_key_result> Function(
              ffi.Int32)>>('frbgen_interactions_cst_new_list_key_result');
  late final _cst_new_list_key_result = _cst_new_list_key_resultPtr
      .asFunction<ffi.Pointer<wire_cst_list_key_result> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_new_list_prim_u_8_strict(
    int len,
  ) {
    return _cst_new_list_prim_u_8_strict(len);
  }

  late final _cst_new_list_prim_u_8_strictPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(
              ffi.Int32)>>('frbgen_interactions_cst_new_list_prim_u_8_strict');
  late final _cst_new_list_prim_u_8_strict = _cst_new_list_prim_u_8_strictPtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(int)>();

  int dummy_method_to_enforce_bundling() {
    return _dummy_method_to_enforce_bundling();
  }

  late final _dummy_method_to_enforce_bundlingPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function()>>(
    'dummy_method_to_enforce_bundling',
  );
  late final _dummy_method_to_enforce_bundling =
      _dummy_method_to_enforce_bundlingPtr.asFunction<int Function()>();
}

typedef DartPostCObjectFnType = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Bool Function(DartPort port_id, ffi.Pointer<ffi.Void> message)>>;
typedef DartPort = ffi.Int64;

final class wire_cst_list_prim_u_8_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_credentials extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> salt;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> pincode_hash;
}

final class wire_cst_list_String extends ffi.Struct {
  external ffi.Pointer<ffi.Pointer<wire_cst_list_prim_u_8_strict>> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_interaction extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  @ffi.Int32()
  external int kind;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> from;

  external ffi.Pointer<wire_cst_list_String> with_members;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> note;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> timestamp;

  @ffi.Bool()
  external bool shared;
}

final class wire_cst_member_credentials extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> email;

  external wire_cst_credentials credentials;
}

final class wire_cst_member extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> email;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> name;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> bio;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> timezone;
}

final class wire_cst_key_result extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> description;

  @ffi.Float()
  external double progress;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> notes;
}

final class wire_cst_list_key_result extends ffi.Struct {
  external ffi.Pointer<wire_cst_key_result> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_objective extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> title;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> description;

  external ffi.Pointer<wire_cst_list_key_result> key_results;

  @ffi.Int32()
  external int visibility;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> owner;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> quarter;
}

final class wire_cst_publish_config extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> manifesto;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> vision;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> okrs;
}

final class wire_cst_webhook_config extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> discord;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> slack;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> signal;
}

final class wire_cst_linting_config extends ffi.Struct {
  @ffi.Bool()
  external bool enabled;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> target_branch;
}

final class wire_cst_backup_config extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> protected_branch;
}

final class wire_cst_team_config extends ffi.Struct {
  external ffi.Pointer<wire_cst_publish_config> publish;

  external ffi.Pointer<wire_cst_webhook_config> webhooks;

  external ffi.Pointer<wire_cst_linting_config> linting;

  external ffi.Pointer<wire_cst_backup_config> backup;
}

final class wire_cst_team extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> name;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> manifesto;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> vision;

  external ffi.Pointer<wire_cst_list_String> leaders;

  external ffi.Pointer<wire_cst_list_String> members;
}
