// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1882716962;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'interactions_ffi',
    ioDirectory: '../rust/ffi/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Credentials crateApiCredentialsCreate({required String pincode});

  Credentials crateApiCredentialsFromYaml({required String yaml});

  String crateApiCredentialsToYaml({required Credentials credentials});

  bool crateApiCredentialsVerify(
      {required Credentials that, required String pincode});

  Interaction crateApiInteractionAppreciation(
      {required String from,
      required List<String> withMembers,
      required String note});

  Interaction crateApiInteractionCreate(
      {required InteractionKind kind,
      required String from,
      required List<String> withMembers,
      required String note});

  Interaction crateApiInteractionFeedback(
      {required String from,
      required List<String> withMembers,
      required String note});

  Interaction crateApiInteractionFromYaml({required String yaml});

  String crateApiInteractionKindLabel({required InteractionKind that});

  String crateApiInteractionToYaml({required Interaction interaction});

  double crateApiKeyResultClampProgress({required double progress});

  KeyResult crateApiKeyResultCreate({required String description});

  Member crateApiMemberCreate({required String email});

  MemberCredentials crateApiMemberCredentialsCreate(
      {required String email, required String pincode});

  MemberCredentials crateApiMemberCredentialsFromYaml({required String yaml});

  String crateApiMemberCredentialsToYaml({required MemberCredentials creds});

  bool crateApiMemberCredentialsVerify(
      {required MemberCredentials that, required String pincode});

  String crateApiMemberDisplayName({required Member that});

  Member crateApiMemberFromYaml({required String yaml});

  String crateApiMemberToYaml({required Member member});

  Objective crateApiObjectiveCreate({required String title});

  Objective crateApiObjectiveFromYaml({required String yaml});

  double crateApiObjectiveOverallProgress({required Objective that});

  String crateApiObjectiveToYaml({required Objective objective});

  Future<OkrVisibility> crateApiOkrVisibilityDefault();

  TeamConfig crateApiTeamConfigCreate();

  TeamConfig crateApiTeamConfigFromYaml({required String yaml});

  String crateApiTeamConfigToYaml({required TeamConfig config});

  TeamConfig crateApiTeamConfigWithDefaults();

  Team crateApiTeamCreate({required String name});

  Team crateApiTeamFromYaml({required String yaml});

  bool crateApiTeamIsLeader({required Team that, required String email});

  bool crateApiTeamIsMember({required Team that, required String email});

  String crateApiTeamToYaml({required Team team});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Credentials crateApiCredentialsCreate({required String pincode}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final arg0 = cst_encode_String(pincode);
        return wire.wire__crate__api__credentials_create(arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_credentials,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiCredentialsCreateConstMeta,
      argValues: [pincode],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCredentialsCreateConstMeta => const TaskConstMeta(
        debugName: 'credentials_create',
        argNames: ['pincode'],
      );

  @override
  Credentials crateApiCredentialsFromYaml({required String yaml}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final arg0 = cst_encode_String(yaml);
        return wire.wire__crate__api__credentials_from_yaml(arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_credentials,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiCredentialsFromYamlConstMeta,
      argValues: [yaml],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCredentialsFromYamlConstMeta =>
      const TaskConstMeta(
        debugName: 'credentials_from_yaml',
        argNames: ['yaml'],
      );

  @override
  String crateApiCredentialsToYaml({required Credentials credentials}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final arg0 = cst_encode_box_autoadd_credentials(credentials);
        return wire.wire__crate__api__credentials_to_yaml(arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_String,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiCredentialsToYamlConstMeta,
      argValues: [credentials],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCredentialsToYamlConstMeta => const TaskConstMeta(
        debugName: 'credentials_to_yaml',
        argNames: ['credentials'],
      );

  @override
  bool crateApiCredentialsVerify(
      {required Credentials that, required String pincode}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final arg0 = cst_encode_box_autoadd_credentials(that);
        final arg1 = cst_encode_String(pincode);
        return wire.wire__crate__api__credentials_verify(arg0, arg1);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCredentialsVerifyConstMeta,
      argValues: [that, pincode],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCredentialsVerifyConstMeta => const TaskConstMeta(
        debugName: 'credentials_verify',
        argNames: ['that', 'pincode'],
      );

  @override
  Interaction crateApiInteractionAppreciation(
      {required String from,
      required List<String> withMembers,
      required String note}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final arg0 = cst_encode_String(from);
        final arg1 = cst_encode_list_String(withMembers);
        final arg2 = cst_encode_String(note);
        return wire.wire__crate__api__interaction_appreciation(
            arg0, arg1, arg2);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_interaction,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiInteractionAppreciationConstMeta,
      argValues: [from, withMembers, note],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInteractionAppreciationConstMeta =>
      const TaskConstMeta(
        debugName: 'interaction_appreciation',
        argNames: ['from', 'withMembers', 'note'],
      );

  @override
  Interaction crateApiInteractionCreate(
      {required InteractionKind kind,
      required String from,
      required List<String> withMembers,
      required String note}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final arg0 = cst_encode_interaction_kind(kind);
        final arg1 = cst_encode_String(from);
        final arg2 = cst_encode_list_String(withMembers);
        final arg3 = cst_encode_String(note);
        return wire.wire__crate__api__interaction_create(
            arg0, arg1, arg2, arg3);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_interaction,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiInteractionCreateConstMeta,
      argValues: [kind, from, withMembers, note],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInteractionCreateConstMeta => const TaskConstMeta(
        debugName: 'interaction_create',
        argNames: ['kind', 'from', 'withMembers', 'note'],
      );

  @override
  Interaction crateApiInteractionFeedback(
      {required String from,
      required List<String> withMembers,
      required String note}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final arg0 = cst_encode_String(from);
        final arg1 = cst_encode_list_String(withMembers);
        final arg2 = cst_encode_String(note);
        return wire.wire__crate__api__interaction_feedback(arg0, arg1, arg2);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_interaction,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiInteractionFeedbackConstMeta,
      argValues: [from, withMembers, note],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInteractionFeedbackConstMeta =>
      const TaskConstMeta(
        debugName: 'interaction_feedback',
        argNames: ['from', 'withMembers', 'note'],
      );

  @override
  Interaction crateApiInteractionFromYaml({required String yaml}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final arg0 = cst_encode_String(yaml);
        return wire.wire__crate__api__interaction_from_yaml(arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_interaction,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiInteractionFromYamlConstMeta,
      argValues: [yaml],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInteractionFromYamlConstMeta =>
      const TaskConstMeta(
        debugName: 'interaction_from_yaml',
        argNames: ['yaml'],
      );

  @override
  String crateApiInteractionKindLabel({required InteractionKind that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final arg0 = cst_encode_interaction_kind(that);
        return wire.wire__crate__api__interaction_kind_label(arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiInteractionKindLabelConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInteractionKindLabelConstMeta =>
      const TaskConstMeta(
        debugName: 'interaction_kind_label',
        argNames: ['that'],
      );

  @override
  String crateApiInteractionToYaml({required Interaction interaction}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final arg0 = cst_encode_box_autoadd_interaction(interaction);
        return wire.wire__crate__api__interaction_to_yaml(arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_String,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiInteractionToYamlConstMeta,
      argValues: [interaction],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInteractionToYamlConstMeta => const TaskConstMeta(
        debugName: 'interaction_to_yaml',
        argNames: ['interaction'],
      );

  @override
  double crateApiKeyResultClampProgress({required double progress}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final arg0 = cst_encode_f_32(progress);
        return wire.wire__crate__api__key_result_clamp_progress(arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_f_32,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiKeyResultClampProgressConstMeta,
      argValues: [progress],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiKeyResultClampProgressConstMeta =>
      const TaskConstMeta(
        debugName: 'key_result_clamp_progress',
        argNames: ['progress'],
      );

  @override
  KeyResult crateApiKeyResultCreate({required String description}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final arg0 = cst_encode_String(description);
        return wire.wire__crate__api__key_result_create(arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_key_result,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiKeyResultCreateConstMeta,
      argValues: [description],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiKeyResultCreateConstMeta => const TaskConstMeta(
        debugName: 'key_result_create',
        argNames: ['description'],
      );

  @override
  Member crateApiMemberCreate({required String email}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final arg0 = cst_encode_String(email);
        return wire.wire__crate__api__member_create(arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_member,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiMemberCreateConstMeta,
      argValues: [email],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMemberCreateConstMeta => const TaskConstMeta(
        debugName: 'member_create',
        argNames: ['email'],
      );

  @override
  MemberCredentials crateApiMemberCredentialsCreate(
      {required String email, required String pincode}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final arg0 = cst_encode_String(email);
        final arg1 = cst_encode_String(pincode);
        return wire.wire__crate__api__member_credentials_create(arg0, arg1);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_member_credentials,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiMemberCredentialsCreateConstMeta,
      argValues: [email, pincode],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMemberCredentialsCreateConstMeta =>
      const TaskConstMeta(
        debugName: 'member_credentials_create',
        argNames: ['email', 'pincode'],
      );

  @override
  MemberCredentials crateApiMemberCredentialsFromYaml({required String yaml}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final arg0 = cst_encode_String(yaml);
        return wire.wire__crate__api__member_credentials_from_yaml(arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_member_credentials,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiMemberCredentialsFromYamlConstMeta,
      argValues: [yaml],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMemberCredentialsFromYamlConstMeta =>
      const TaskConstMeta(
        debugName: 'member_credentials_from_yaml',
        argNames: ['yaml'],
      );

  @override
  String crateApiMemberCredentialsToYaml({required MemberCredentials creds}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final arg0 = cst_encode_box_autoadd_member_credentials(creds);
        return wire.wire__crate__api__member_credentials_to_yaml(arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_String,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiMemberCredentialsToYamlConstMeta,
      argValues: [creds],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMemberCredentialsToYamlConstMeta =>
      const TaskConstMeta(
        debugName: 'member_credentials_to_yaml',
        argNames: ['creds'],
      );

  @override
  bool crateApiMemberCredentialsVerify(
      {required MemberCredentials that, required String pincode}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final arg0 = cst_encode_box_autoadd_member_credentials(that);
        final arg1 = cst_encode_String(pincode);
        return wire.wire__crate__api__member_credentials_verify(arg0, arg1);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiMemberCredentialsVerifyConstMeta,
      argValues: [that, pincode],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMemberCredentialsVerifyConstMeta =>
      const TaskConstMeta(
        debugName: 'member_credentials_verify',
        argNames: ['that', 'pincode'],
      );

  @override
  String crateApiMemberDisplayName({required Member that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final arg0 = cst_encode_box_autoadd_member(that);
        return wire.wire__crate__api__member_display_name(arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiMemberDisplayNameConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMemberDisplayNameConstMeta => const TaskConstMeta(
        debugName: 'member_display_name',
        argNames: ['that'],
      );

  @override
  Member crateApiMemberFromYaml({required String yaml}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final arg0 = cst_encode_String(yaml);
        return wire.wire__crate__api__member_from_yaml(arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_member,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiMemberFromYamlConstMeta,
      argValues: [yaml],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMemberFromYamlConstMeta => const TaskConstMeta(
        debugName: 'member_from_yaml',
        argNames: ['yaml'],
      );

  @override
  String crateApiMemberToYaml({required Member member}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final arg0 = cst_encode_box_autoadd_member(member);
        return wire.wire__crate__api__member_to_yaml(arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_String,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiMemberToYamlConstMeta,
      argValues: [member],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMemberToYamlConstMeta => const TaskConstMeta(
        debugName: 'member_to_yaml',
        argNames: ['member'],
      );

  @override
  Objective crateApiObjectiveCreate({required String title}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final arg0 = cst_encode_String(title);
        return wire.wire__crate__api__objective_create(arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_objective,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiObjectiveCreateConstMeta,
      argValues: [title],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiObjectiveCreateConstMeta => const TaskConstMeta(
        debugName: 'objective_create',
        argNames: ['title'],
      );

  @override
  Objective crateApiObjectiveFromYaml({required String yaml}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final arg0 = cst_encode_String(yaml);
        return wire.wire__crate__api__objective_from_yaml(arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_objective,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiObjectiveFromYamlConstMeta,
      argValues: [yaml],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiObjectiveFromYamlConstMeta => const TaskConstMeta(
        debugName: 'objective_from_yaml',
        argNames: ['yaml'],
      );

  @override
  double crateApiObjectiveOverallProgress({required Objective that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final arg0 = cst_encode_box_autoadd_objective(that);
        return wire.wire__crate__api__objective_overall_progress(arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_f_32,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiObjectiveOverallProgressConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiObjectiveOverallProgressConstMeta =>
      const TaskConstMeta(
        debugName: 'objective_overall_progress',
        argNames: ['that'],
      );

  @override
  String crateApiObjectiveToYaml({required Objective objective}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final arg0 = cst_encode_box_autoadd_objective(objective);
        return wire.wire__crate__api__objective_to_yaml(arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_String,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiObjectiveToYamlConstMeta,
      argValues: [objective],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiObjectiveToYamlConstMeta => const TaskConstMeta(
        debugName: 'objective_to_yaml',
        argNames: ['objective'],
      );

  @override
  Future<OkrVisibility> crateApiOkrVisibilityDefault() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        return wire.wire__crate__api__okr_visibility_default(port_);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_okr_visibility,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiOkrVisibilityDefaultConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiOkrVisibilityDefaultConstMeta =>
      const TaskConstMeta(
        debugName: 'okr_visibility_default',
        argNames: [],
      );

  @override
  TeamConfig crateApiTeamConfigCreate() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        return wire.wire__crate__api__team_config_create();
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_team_config,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiTeamConfigCreateConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTeamConfigCreateConstMeta => const TaskConstMeta(
        debugName: 'team_config_create',
        argNames: [],
      );

  @override
  TeamConfig crateApiTeamConfigFromYaml({required String yaml}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final arg0 = cst_encode_String(yaml);
        return wire.wire__crate__api__team_config_from_yaml(arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_team_config,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiTeamConfigFromYamlConstMeta,
      argValues: [yaml],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTeamConfigFromYamlConstMeta => const TaskConstMeta(
        debugName: 'team_config_from_yaml',
        argNames: ['yaml'],
      );

  @override
  String crateApiTeamConfigToYaml({required TeamConfig config}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final arg0 = cst_encode_box_autoadd_team_config(config);
        return wire.wire__crate__api__team_config_to_yaml(arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_String,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiTeamConfigToYamlConstMeta,
      argValues: [config],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTeamConfigToYamlConstMeta => const TaskConstMeta(
        debugName: 'team_config_to_yaml',
        argNames: ['config'],
      );

  @override
  TeamConfig crateApiTeamConfigWithDefaults() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        return wire.wire__crate__api__team_config_with_defaults();
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_team_config,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiTeamConfigWithDefaultsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTeamConfigWithDefaultsConstMeta =>
      const TaskConstMeta(
        debugName: 'team_config_with_defaults',
        argNames: [],
      );

  @override
  Team crateApiTeamCreate({required String name}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final arg0 = cst_encode_String(name);
        return wire.wire__crate__api__team_create(arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_team,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiTeamCreateConstMeta,
      argValues: [name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTeamCreateConstMeta => const TaskConstMeta(
        debugName: 'team_create',
        argNames: ['name'],
      );

  @override
  Team crateApiTeamFromYaml({required String yaml}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final arg0 = cst_encode_String(yaml);
        return wire.wire__crate__api__team_from_yaml(arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_team,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiTeamFromYamlConstMeta,
      argValues: [yaml],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTeamFromYamlConstMeta => const TaskConstMeta(
        debugName: 'team_from_yaml',
        argNames: ['yaml'],
      );

  @override
  bool crateApiTeamIsLeader({required Team that, required String email}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final arg0 = cst_encode_box_autoadd_team(that);
        final arg1 = cst_encode_String(email);
        return wire.wire__crate__api__team_is_leader(arg0, arg1);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiTeamIsLeaderConstMeta,
      argValues: [that, email],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTeamIsLeaderConstMeta => const TaskConstMeta(
        debugName: 'team_is_leader',
        argNames: ['that', 'email'],
      );

  @override
  bool crateApiTeamIsMember({required Team that, required String email}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final arg0 = cst_encode_box_autoadd_team(that);
        final arg1 = cst_encode_String(email);
        return wire.wire__crate__api__team_is_member(arg0, arg1);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiTeamIsMemberConstMeta,
      argValues: [that, email],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTeamIsMemberConstMeta => const TaskConstMeta(
        debugName: 'team_is_member',
        argNames: ['that', 'email'],
      );

  @override
  String crateApiTeamToYaml({required Team team}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final arg0 = cst_encode_box_autoadd_team(team);
        return wire.wire__crate__api__team_to_yaml(arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_String,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiTeamToYamlConstMeta,
      argValues: [team],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTeamToYamlConstMeta => const TaskConstMeta(
        debugName: 'team_to_yaml',
        argNames: ['team'],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BackupConfig dco_decode_backup_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return BackupConfig(
      protectedBranch: dco_decode_opt_String(arr[0]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BackupConfig dco_decode_box_autoadd_backup_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_backup_config(raw);
  }

  @protected
  Credentials dco_decode_box_autoadd_credentials(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_credentials(raw);
  }

  @protected
  Interaction dco_decode_box_autoadd_interaction(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_interaction(raw);
  }

  @protected
  LintingConfig dco_decode_box_autoadd_linting_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_linting_config(raw);
  }

  @protected
  Member dco_decode_box_autoadd_member(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_member(raw);
  }

  @protected
  MemberCredentials dco_decode_box_autoadd_member_credentials(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_member_credentials(raw);
  }

  @protected
  Objective dco_decode_box_autoadd_objective(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_objective(raw);
  }

  @protected
  PublishConfig dco_decode_box_autoadd_publish_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_publish_config(raw);
  }

  @protected
  Team dco_decode_box_autoadd_team(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_team(raw);
  }

  @protected
  TeamConfig dco_decode_box_autoadd_team_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_team_config(raw);
  }

  @protected
  WebhookConfig dco_decode_box_autoadd_webhook_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_webhook_config(raw);
  }

  @protected
  Credentials dco_decode_credentials(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return Credentials(
      salt: dco_decode_String(arr[0]),
      pincodeHash: dco_decode_String(arr[1]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Interaction dco_decode_interaction(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return Interaction(
      id: dco_decode_String(arr[0]),
      kind: dco_decode_interaction_kind(arr[1]),
      from: dco_decode_String(arr[2]),
      withMembers: dco_decode_list_String(arr[3]),
      note: dco_decode_String(arr[4]),
      timestamp: dco_decode_String(arr[5]),
      shared: dco_decode_bool(arr[6]),
    );
  }

  @protected
  InteractionKind dco_decode_interaction_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return InteractionKind.values[raw as int];
  }

  @protected
  KeyResult dco_decode_key_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return KeyResult(
      description: dco_decode_String(arr[0]),
      progress: dco_decode_f_32(arr[1]),
      notes: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  LintingConfig dco_decode_linting_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return LintingConfig(
      enabled: dco_decode_bool(arr[0]),
      targetBranch: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<KeyResult> dco_decode_list_key_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_key_result).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  Member dco_decode_member(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return Member(
      email: dco_decode_String(arr[0]),
      name: dco_decode_opt_String(arr[1]),
      bio: dco_decode_opt_String(arr[2]),
      timezone: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  MemberCredentials dco_decode_member_credentials(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return MemberCredentials(
      email: dco_decode_String(arr[0]),
      credentials: dco_decode_credentials(arr[1]),
    );
  }

  @protected
  Objective dco_decode_objective(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return Objective(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      description: dco_decode_opt_String(arr[2]),
      keyResults: dco_decode_list_key_result(arr[3]),
      visibility: dco_decode_okr_visibility(arr[4]),
      owner: dco_decode_opt_String(arr[5]),
      quarter: dco_decode_opt_String(arr[6]),
    );
  }

  @protected
  OkrVisibility dco_decode_okr_visibility(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return OkrVisibility.values[raw as int];
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  BackupConfig? dco_decode_opt_box_autoadd_backup_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_backup_config(raw);
  }

  @protected
  LintingConfig? dco_decode_opt_box_autoadd_linting_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_linting_config(raw);
  }

  @protected
  PublishConfig? dco_decode_opt_box_autoadd_publish_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_publish_config(raw);
  }

  @protected
  WebhookConfig? dco_decode_opt_box_autoadd_webhook_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_webhook_config(raw);
  }

  @protected
  PublishConfig dco_decode_publish_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return PublishConfig(
      manifesto: dco_decode_opt_String(arr[0]),
      vision: dco_decode_opt_String(arr[1]),
      okrs: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  Team dco_decode_team(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return Team(
      name: dco_decode_String(arr[0]),
      manifesto: dco_decode_opt_String(arr[1]),
      vision: dco_decode_opt_String(arr[2]),
      leaders: dco_decode_list_String(arr[3]),
      members: dco_decode_list_String(arr[4]),
    );
  }

  @protected
  TeamConfig dco_decode_team_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return TeamConfig(
      publish: dco_decode_opt_box_autoadd_publish_config(arr[0]),
      webhooks: dco_decode_opt_box_autoadd_webhook_config(arr[1]),
      linting: dco_decode_opt_box_autoadd_linting_config(arr[2]),
      backup: dco_decode_opt_box_autoadd_backup_config(arr[3]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  WebhookConfig dco_decode_webhook_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return WebhookConfig(
      discord: dco_decode_opt_String(arr[0]),
      slack: dco_decode_opt_String(arr[1]),
      signal: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BackupConfig sse_decode_backup_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_protectedBranch = sse_decode_opt_String(deserializer);
    return BackupConfig(protectedBranch: var_protectedBranch);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BackupConfig sse_decode_box_autoadd_backup_config(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_backup_config(deserializer));
  }

  @protected
  Credentials sse_decode_box_autoadd_credentials(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_credentials(deserializer));
  }

  @protected
  Interaction sse_decode_box_autoadd_interaction(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_interaction(deserializer));
  }

  @protected
  LintingConfig sse_decode_box_autoadd_linting_config(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_linting_config(deserializer));
  }

  @protected
  Member sse_decode_box_autoadd_member(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_member(deserializer));
  }

  @protected
  MemberCredentials sse_decode_box_autoadd_member_credentials(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_member_credentials(deserializer));
  }

  @protected
  Objective sse_decode_box_autoadd_objective(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_objective(deserializer));
  }

  @protected
  PublishConfig sse_decode_box_autoadd_publish_config(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_publish_config(deserializer));
  }

  @protected
  Team sse_decode_box_autoadd_team(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_team(deserializer));
  }

  @protected
  TeamConfig sse_decode_box_autoadd_team_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_team_config(deserializer));
  }

  @protected
  WebhookConfig sse_decode_box_autoadd_webhook_config(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_webhook_config(deserializer));
  }

  @protected
  Credentials sse_decode_credentials(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_salt = sse_decode_String(deserializer);
    final var_pincodeHash = sse_decode_String(deserializer);
    return Credentials(salt: var_salt, pincodeHash: var_pincodeHash);
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  Interaction sse_decode_interaction(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_id = sse_decode_String(deserializer);
    final var_kind = sse_decode_interaction_kind(deserializer);
    final var_from = sse_decode_String(deserializer);
    final var_withMembers = sse_decode_list_String(deserializer);
    final var_note = sse_decode_String(deserializer);
    final var_timestamp = sse_decode_String(deserializer);
    final var_shared = sse_decode_bool(deserializer);
    return Interaction(
        id: var_id,
        kind: var_kind,
        from: var_from,
        withMembers: var_withMembers,
        note: var_note,
        timestamp: var_timestamp,
        shared: var_shared);
  }

  @protected
  InteractionKind sse_decode_interaction_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final inner = sse_decode_i_32(deserializer);
    return InteractionKind.values[inner];
  }

  @protected
  KeyResult sse_decode_key_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_description = sse_decode_String(deserializer);
    final var_progress = sse_decode_f_32(deserializer);
    final var_notes = sse_decode_opt_String(deserializer);
    return KeyResult(
        description: var_description, progress: var_progress, notes: var_notes);
  }

  @protected
  LintingConfig sse_decode_linting_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_enabled = sse_decode_bool(deserializer);
    final var_targetBranch = sse_decode_opt_String(deserializer);
    return LintingConfig(enabled: var_enabled, targetBranch: var_targetBranch);
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    final len_ = sse_decode_i_32(deserializer);
    final ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<KeyResult> sse_decode_list_key_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    final len_ = sse_decode_i_32(deserializer);
    final ans_ = <KeyResult>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_key_result(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Member sse_decode_member(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_email = sse_decode_String(deserializer);
    final var_name = sse_decode_opt_String(deserializer);
    final var_bio = sse_decode_opt_String(deserializer);
    final var_timezone = sse_decode_opt_String(deserializer);
    return Member(
        email: var_email, name: var_name, bio: var_bio, timezone: var_timezone);
  }

  @protected
  MemberCredentials sse_decode_member_credentials(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_email = sse_decode_String(deserializer);
    final var_credentials = sse_decode_credentials(deserializer);
    return MemberCredentials(email: var_email, credentials: var_credentials);
  }

  @protected
  Objective sse_decode_objective(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_id = sse_decode_String(deserializer);
    final var_title = sse_decode_String(deserializer);
    final var_description = sse_decode_opt_String(deserializer);
    final var_keyResults = sse_decode_list_key_result(deserializer);
    final var_visibility = sse_decode_okr_visibility(deserializer);
    final var_owner = sse_decode_opt_String(deserializer);
    final var_quarter = sse_decode_opt_String(deserializer);
    return Objective(
        id: var_id,
        title: var_title,
        description: var_description,
        keyResults: var_keyResults,
        visibility: var_visibility,
        owner: var_owner,
        quarter: var_quarter);
  }

  @protected
  OkrVisibility sse_decode_okr_visibility(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final inner = sse_decode_i_32(deserializer);
    return OkrVisibility.values[inner];
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BackupConfig? sse_decode_opt_box_autoadd_backup_config(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_backup_config(deserializer));
    } else {
      return null;
    }
  }

  @protected
  LintingConfig? sse_decode_opt_box_autoadd_linting_config(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_linting_config(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PublishConfig? sse_decode_opt_box_autoadd_publish_config(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_publish_config(deserializer));
    } else {
      return null;
    }
  }

  @protected
  WebhookConfig? sse_decode_opt_box_autoadd_webhook_config(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_webhook_config(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PublishConfig sse_decode_publish_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_manifesto = sse_decode_opt_String(deserializer);
    final var_vision = sse_decode_opt_String(deserializer);
    final var_okrs = sse_decode_opt_String(deserializer);
    return PublishConfig(
        manifesto: var_manifesto, vision: var_vision, okrs: var_okrs);
  }

  @protected
  Team sse_decode_team(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_name = sse_decode_String(deserializer);
    final var_manifesto = sse_decode_opt_String(deserializer);
    final var_vision = sse_decode_opt_String(deserializer);
    final var_leaders = sse_decode_list_String(deserializer);
    final var_members = sse_decode_list_String(deserializer);
    return Team(
        name: var_name,
        manifesto: var_manifesto,
        vision: var_vision,
        leaders: var_leaders,
        members: var_members);
  }

  @protected
  TeamConfig sse_decode_team_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_publish = sse_decode_opt_box_autoadd_publish_config(deserializer);
    final var_webhooks =
        sse_decode_opt_box_autoadd_webhook_config(deserializer);
    final var_linting = sse_decode_opt_box_autoadd_linting_config(deserializer);
    final var_backup = sse_decode_opt_box_autoadd_backup_config(deserializer);
    return TeamConfig(
        publish: var_publish,
        webhooks: var_webhooks,
        linting: var_linting,
        backup: var_backup);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  WebhookConfig sse_decode_webhook_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_discord = sse_decode_opt_String(deserializer);
    final var_slack = sse_decode_opt_String(deserializer);
    final var_signal = sse_decode_opt_String(deserializer);
    return WebhookConfig(
        discord: var_discord, slack: var_slack, signal: var_signal);
  }

  @protected
  bool cst_encode_bool(bool raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  double cst_encode_f_32(double raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_i_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_interaction_kind(InteractionKind raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_32(raw.index);
  }

  @protected
  int cst_encode_okr_visibility(OkrVisibility raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_32(raw.index);
  }

  @protected
  int cst_encode_u_8(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void cst_encode_unit(void raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_backup_config(BackupConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.protectedBranch, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_backup_config(
      BackupConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_backup_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_credentials(
      Credentials self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_credentials(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_interaction(
      Interaction self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_interaction(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_linting_config(
      LintingConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_linting_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_member(Member self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_member(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_member_credentials(
      MemberCredentials self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_member_credentials(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_objective(
      Objective self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_objective(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_publish_config(
      PublishConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_publish_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_team(Team self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_team(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_team_config(
      TeamConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_team_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_webhook_config(
      WebhookConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_webhook_config(self, serializer);
  }

  @protected
  void sse_encode_credentials(Credentials self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.salt, serializer);
    sse_encode_String(self.pincodeHash, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_interaction(Interaction self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_interaction_kind(self.kind, serializer);
    sse_encode_String(self.from, serializer);
    sse_encode_list_String(self.withMembers, serializer);
    sse_encode_String(self.note, serializer);
    sse_encode_String(self.timestamp, serializer);
    sse_encode_bool(self.shared, serializer);
  }

  @protected
  void sse_encode_interaction_kind(
      InteractionKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_key_result(KeyResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.description, serializer);
    sse_encode_f_32(self.progress, serializer);
    sse_encode_opt_String(self.notes, serializer);
  }

  @protected
  void sse_encode_linting_config(LintingConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.enabled, serializer);
    sse_encode_opt_String(self.targetBranch, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_key_result(
      List<KeyResult> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_key_result(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_member(Member self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.email, serializer);
    sse_encode_opt_String(self.name, serializer);
    sse_encode_opt_String(self.bio, serializer);
    sse_encode_opt_String(self.timezone, serializer);
  }

  @protected
  void sse_encode_member_credentials(
      MemberCredentials self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.email, serializer);
    sse_encode_credentials(self.credentials, serializer);
  }

  @protected
  void sse_encode_objective(Objective self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_opt_String(self.description, serializer);
    sse_encode_list_key_result(self.keyResults, serializer);
    sse_encode_okr_visibility(self.visibility, serializer);
    sse_encode_opt_String(self.owner, serializer);
    sse_encode_opt_String(self.quarter, serializer);
  }

  @protected
  void sse_encode_okr_visibility(OkrVisibility self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_backup_config(
      BackupConfig? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_backup_config(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_linting_config(
      LintingConfig? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_linting_config(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_publish_config(
      PublishConfig? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_publish_config(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_webhook_config(
      WebhookConfig? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_webhook_config(self, serializer);
    }
  }

  @protected
  void sse_encode_publish_config(PublishConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.manifesto, serializer);
    sse_encode_opt_String(self.vision, serializer);
    sse_encode_opt_String(self.okrs, serializer);
  }

  @protected
  void sse_encode_team(Team self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_opt_String(self.manifesto, serializer);
    sse_encode_opt_String(self.vision, serializer);
    sse_encode_list_String(self.leaders, serializer);
    sse_encode_list_String(self.members, serializer);
  }

  @protected
  void sse_encode_team_config(TeamConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_publish_config(self.publish, serializer);
    sse_encode_opt_box_autoadd_webhook_config(self.webhooks, serializer);
    sse_encode_opt_box_autoadd_linting_config(self.linting, serializer);
    sse_encode_opt_box_autoadd_backup_config(self.backup, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_webhook_config(WebhookConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.discord, serializer);
    sse_encode_opt_String(self.slack, serializer);
    sse_encode_opt_String(self.signal, serializer);
  }
}
